#!/usr/bin/env ruby

#  e.g. rake pdf                 # Create a PDF
#       rake xhtml               # Create an XHTML file
#       rake chm                 # Create a CHM help file
#       rake pdf VALIDATE=false  # skips validation


#=================== Set path to DOCBOOK files =======
DOCBOOK_ROOT = ENV['SHORT_ATTENTION_SPAN_DOCBOOK_PATH'] ||  "/Users/brianhogan/git/docbook"
require "#{DOCBOOK_ROOT}/make"

